# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Combiner.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionSearch_single_id = QtWidgets.QAction(MainWindow)
        self.actionSearch_single_id.setObjectName("actionSearch_single_id")
        self.actionSearch_IDs = QtWidgets.QAction(MainWindow)
        self.actionSearch_IDs.setObjectName("actionSearch_IDs")
        self.menuFile.addAction(self.actionOpen_folder)
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionExit_2)
        self.menuSearch.addAction(self.actionSearch_single_id)
        self.menuSearch.addAction(self.actionSearch_IDs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSearch.setTitle(_translate("MainWindow", "Search"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.actionOpen_folder.setText(_translate("MainWindow", "Open folder"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
        self.actionExit.setText(_translate("MainWindow", "Open reference folder"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionSearch_single_id.setText(_translate("MainWindow", "Search single id"))
        self.actionSearch_IDs.setText(_translate("MainWindow", "Search IDs"))
