# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtGui import QIcon
import sys
from plugin.OK2Ship_Gui import OK2Ship_Reviewer_GUI
from OK2Ship_Reviewer import OK2D_Sorter


class CTDA_MainWindow(QMainWindow):
    def __init__(self, version_id, author_id = 'Amazon SQM'):
        super(CTDA_MainWindow, self).__init__()
        self.resize(800, 600)
        self.setWindowTitle("Camera Test Data Analyst %s - By %s" % (version_id, author_id))
        self.setWindowIcon(QIcon('image/iconmonstr-photo-camera-8.svg'))

        self.setupUi(author_id)

    def setupUi(self, author_id):
        # self.setObjectName("MainWindow")

        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 621, 81))
        self.label.setText("Camera Test Data Analyst")
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")



        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("By %s" % author_id)
        self.label_2.setGeometry(QtCore.QRect(530, 140, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 180, 491, 341))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setIcon(QIcon('image/data_analysis.ico'))
        self.pushButton.setText("Data Analysis")
        self.pushButton.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton.setMaximumSize(QtCore.QSize(500, 36))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.call_combiner)
        self.verticalLayout.addWidget(self.pushButton)

        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setIcon(QIcon('image/delivery.ico'))
        self.pushButton_2.setText("OK2Delivery Reviewer")
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton_2.setMaximumSize(QtCore.QSize(500, 36))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.call_sorter)
        self.verticalLayout.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setText("SFR Analyst")
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton_3.setMaximumSize(QtCore.QSize(500, 36))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setText('Blemish Coordinate Analysis')
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton_4.setMaximumSize(QtCore.QSize(500, 36))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(self)

    def call_combiner(self):
        self.close()
        dC = dataCombiner()
        dC.wm_attributes('-topmost', 0)
        dC.mainloop()
        sys.exit(0)

    def call_sorter(self):
        self.close()
        Sorter = OK2Ship_Reviewer_GUI()
        Sorter.wm_attributes('-topmost', 0)
        Sorter.show()
        # self.deiconify()
        sys.exit(0)

    def call_sfr_analyst(self):
        pass

    def call_blemish_coor_analyst(self):
        pass

    def self_quit(self):
        self.close()
        sys.exit(0)

